name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  main:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Install dependencies
        run: npm ci

      - name: Build
        run: MUSICKIT_TOKEN=${{ secrets.MK_TOKEN}} npm run build

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_STARTRACK_NG }}'
          projectId: startrack-ng
          channelId: live
